// src/app/pages/settings/settings.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Subscription } from 'rxjs';
import { SettingsService } from '../../services/settings.service';
import { InventorySyncService, SyncResult as InventorySyncResult } from '../../services/inventory-sync.service';
import { PartListSyncService, SyncResult as PartListSyncResult } from '../../services/part-list-sync.service';
import { ApiSyncService, ApiSyncResult, ApiSyncProgress } from '../../services/api-sync.service';
import { ExcelService } from '../../services/excel.service';
import { OfflineService } from '../../services/offline.service';
import { UserSettings } from '../../models';

@Component({
  selector: 'app-settings',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div>
      <div class="mb-4">
        <h1 class="h3 fw-bold mb-1">Settings</h1>
        <p class="text-muted mb-0">Configure your preferences and manage data</p>
      </div>

      <div class="row">
        <div class="col-lg-6">
          <!-- User Settings -->
          <div class="card mb-4">
            <div class="card-header">
              <span class="fw-semibold">
                <i class="bi bi-person me-2"></i>User Settings
              </span>
            </div>
            <div class="card-body">
              <div class="mb-3">
                <label class="form-label">Your Name</label>
                <input type="text" class="form-control" placeholder="Enter your name"
                       [(ngModel)]="userName"
                       (blur)="saveUserName()">
                <div class="form-text">This name will be recorded when you pick items</div>
              </div>
            </div>
          </div>

          <!-- Theme Settings -->
          <div class="card mb-4">
            <div class="card-header">
              <span class="fw-semibold">
                <i class="bi bi-palette me-2"></i>Appearance
              </span>
            </div>
            <div class="card-body">
              <div class="mb-3">
                <label class="form-label">Theme</label>
                <select class="form-select" [(ngModel)]="theme" (change)="saveTheme()">
                  <option value="light">Light</option>
                  <option value="dark">Dark</option>
                  <option value="system">System (auto)</option>
                </select>
                <div class="form-text">Choose your preferred color scheme</div>
              </div>
            </div>
          </div>

          <!-- Tag Printing -->
          <div class="card mb-4">
            <div class="card-header">
              <span class="fw-semibold">
                <i class="bi bi-printer me-2"></i>Tag Printing
              </span>
            </div>
            <div class="card-body">
              <div class="d-flex align-items-center justify-content-between mb-3">
                <div>
                  <div class="fw-medium">Enable Tag Printing</div>
                  <div class="form-text">Show print dialog after picking parts</div>
                </div>
                <div class="form-check form-switch">
                  <input class="form-check-input" type="checkbox" role="switch"
                         [(ngModel)]="tagPrintingEnabled"
                         (change)="saveTagPrinting()">
                </div>
              </div>

              <div class="small text-muted">
                <div class="fw-medium text-body mb-2">Printer Setup:</div>
                <ul class="ps-3 mb-2">
                  <li><strong>Printer:</strong> Brother P-Touch QL500</li>
                  <li><strong>Label Size:</strong> 0.66" x 3.4" (landscape)</li>
                  <li>Each part/tool combination gets one tag</li>
                </ul>
                <div class="alert alert-light small py-2 mb-0">
                  <i class="bi bi-lightbulb me-1"></i>
                  Tip: Set the Brother QL500 as your default printer for faster printing.
                </div>
              </div>
            </div>
          </div>

          <!-- App Status -->
          <div class="card mb-4">
            <div class="card-header">
              <span class="fw-semibold">
                <i class="bi bi-wifi me-2"></i>App Status
              </span>
            </div>
            <div class="card-body">
              <!-- Connection Status -->
              <div class="d-flex align-items-center justify-content-between mb-3">
                <span>Connection Status</span>
                <span [class]="isOnline ? 'badge bg-success' : 'badge bg-danger'">
                  <i [class]="isOnline ? 'bi bi-wifi me-1' : 'bi bi-wifi-off me-1'"></i>
                  {{ isOnline ? 'Online' : 'Offline' }}
                </span>
              </div>

              <!-- Offline Queue -->
              <div class="d-flex align-items-center justify-content-between mb-3">
                <span>Offline Queue</span>
                <span class="badge" [class]="offlineQueueCount > 0 ? 'bg-warning text-dark' : 'bg-secondary'">
                  {{ offlineQueueCount }} pending {{ offlineQueueCount === 1 ? 'pick' : 'picks' }}
                </span>
              </div>

              <!-- Sync Button -->
              <button
                *ngIf="offlineQueueCount > 0"
                class="btn btn-warning w-100 mb-3"
                [disabled]="isSyncing || !isOnline"
                (click)="syncOfflineQueue()"
              >
                <i class="bi bi-cloud-upload me-2" [class.spin]="isSyncing"></i>
                {{ isSyncing ? 'Syncing...' : 'Sync Offline Picks' }}
              </button>

              <!-- PWA Install -->
              <div class="d-flex align-items-center justify-content-between">
                <span>Install as App</span>
                <button
                  class="btn btn-sm btn-outline-primary"
                  [disabled]="!canInstallPwa"
                  (click)="installPwa()"
                >
                  <i class="bi bi-download me-1"></i>
                  Install
                </button>
              </div>
              <div class="form-text" *ngIf="!canInstallPwa">
                App is already installed or not installable in this browser
              </div>
            </div>
          </div>

          <!-- About -->
          <div class="card">
            <div class="card-header">
              <span class="fw-semibold">
                <i class="bi bi-info-circle me-2"></i>About
              </span>
            </div>
            <div class="card-body">
              <p class="mb-2"><strong>Tool Pick List Tracker</strong></p>
              <p class="text-muted small mb-2">
                A comprehensive application for managing pick lists and tracking picking progress for sales orders.
              </p>
              <p class="text-muted small mb-0">
                Built with Angular and Bootstrap. Data stored in Supabase.
              </p>
            </div>
          </div>
        </div>

        <div class="col-lg-6">
          <!-- Inventory Sync -->
          <div class="card mb-4">
            <div class="card-header">
              <span class="fw-semibold">
                <i class="bi bi-box-seam me-2"></i>Inventory Sync
              </span>
            </div>
            <div class="card-body">
              <p class="small text-muted mb-3">
                Upload an inventory Excel file to update stock quantities and locations.
                Expected columns: Product ID, Lot ID, Location, Qty Available.
              </p>

              <div class="mb-3">
                <input
                  type="file"
                  class="form-control"
                  accept=".xlsx,.xls"
                  (change)="onInventoryFileSelected($event)"
                  #inventoryFileInput
                >
              </div>

              <button
                class="btn btn-primary w-100"
                [disabled]="!inventoryFile || inventorySyncing"
                (click)="syncInventory()"
              >
                <i class="bi me-2" [class]="inventorySyncing ? 'bi-arrow-clockwise spin' : 'bi-cloud-upload'"></i>
                {{ inventorySyncing ? 'Syncing...' : 'Sync Inventory' }}
              </button>

              <!-- Inventory Sync Results -->
              <div *ngIf="inventorySyncResult" class="mt-3">
                <div [class]="inventorySyncResult.success ? 'alert alert-success' : 'alert alert-warning'" class="small mb-2">
                  <div class="fw-semibold mb-1">
                    {{ inventorySyncResult.success ? 'Sync Complete' : 'Sync Completed with Issues' }}
                  </div>
                  <div>Updated: {{ inventorySyncResult.updatedCount }} line items</div>
                  <div>Not found: {{ inventorySyncResult.notFoundCount }} line items</div>
                </div>

                <div *ngIf="inventorySyncResult.errors.length > 0" class="alert alert-danger small mb-2">
                  <div class="fw-semibold mb-1">Errors:</div>
                  <ul class="mb-0 ps-3">
                    <li *ngFor="let error of inventorySyncResult.errors">{{ error }}</li>
                  </ul>
                </div>

                <div *ngIf="inventorySyncResult.notFoundParts.length > 0">
                  <button
                    class="btn btn-sm btn-outline-secondary"
                    type="button"
                    (click)="showNotFoundParts = !showNotFoundParts"
                  >
                    {{ showNotFoundParts ? 'Hide' : 'Show' }} {{ inventorySyncResult.notFoundParts.length }} not found parts
                  </button>
                  <div *ngIf="showNotFoundParts" class="mt-2 p-2 bg-body-secondary rounded small" style="max-height: 150px; overflow-y: auto;">
                    <code *ngFor="let part of inventorySyncResult.notFoundParts; let last = last">
                      {{ part }}{{ last ? '' : ', ' }}
                    </code>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <!-- Part List Sync -->
          <div class="card mb-4">
            <div class="card-header">
              <span class="fw-semibold">
                <i class="bi bi-list-check me-2"></i>Part List Sync
              </span>
            </div>
            <div class="card-body">
              <p class="small text-muted mb-3">
                Upload a Part List Excel file to update locations, descriptions, and quantities.
                Expected columns: Product ID, Location, Qty Available, Qty On Order, Description.
              </p>

              <div class="mb-3">
                <input
                  type="file"
                  class="form-control"
                  accept=".xlsx,.xls"
                  (change)="onPartListFileSelected($event)"
                  #partListFileInput
                >
              </div>

              <button
                class="btn btn-primary w-100"
                [disabled]="!partListFile || partListSyncing"
                (click)="syncPartList()"
              >
                <i class="bi me-2" [class]="partListSyncing ? 'bi-arrow-clockwise spin' : 'bi-cloud-upload'"></i>
                {{ partListSyncing ? 'Syncing...' : 'Sync Part List' }}
              </button>

              <!-- Part List Sync Results -->
              <div *ngIf="partListSyncResult" class="mt-3">
                <div [class]="partListSyncResult.success ? 'alert alert-success' : 'alert alert-warning'" class="small mb-2">
                  <div class="fw-semibold mb-1">
                    {{ partListSyncResult.success ? 'Sync Complete' : 'Sync Completed with Issues' }}
                  </div>
                  <div>Updated: {{ partListSyncResult.updatedCount }} line items</div>
                  <div>Not found: {{ partListSyncResult.notFoundCount }} line items</div>
                </div>

                <div *ngIf="partListSyncResult.errors.length > 0" class="alert alert-danger small mb-2">
                  <div class="fw-semibold mb-1">Errors:</div>
                  <ul class="mb-0 ps-3">
                    <li *ngFor="let error of partListSyncResult.errors">{{ error }}</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>

          <!-- API Sync -->
          <div class="card mb-4">
            <div class="card-header">
              <span class="fw-semibold">
                <i class="bi bi-globe me-2"></i>API Sync
              </span>
            </div>
            <div class="card-body">
              <p class="small text-muted mb-3">
                Sync qty available, qty on order, and descriptions directly from the Andrews Tool API.
              </p>

              <div class="mb-3">
                <label class="form-label small">
                  <i class="bi bi-lock me-1"></i>Password Required
                </label>
                <div class="d-flex gap-2">
                  <input
                    type="password"
                    class="form-control"
                    placeholder="Enter sync password"
                    [(ngModel)]="apiPassword"
                  >
                  <button
                    class="btn btn-primary flex-shrink-0"
                    [disabled]="!isApiPasswordCorrect || apiSyncing"
                    (click)="syncFromApi()"
                  >
                    <i class="bi me-1" [class]="apiSyncing ? 'bi-arrow-clockwise spin' : 'bi-globe'"></i>
                    {{ apiSyncing ? 'Syncing...' : 'Sync from API' }}
                  </button>
                </div>
              </div>

              <!-- Progress -->
              <div *ngIf="apiSyncing && apiProgress" class="mb-3">
                <div class="d-flex justify-content-between small mb-1">
                  <span class="text-muted">{{ apiProgress.status }}</span>
                  <span class="fw-medium">{{ apiProgress.currentBatch }} / {{ apiProgress.totalBatches }}</span>
                </div>
                <div class="progress">
                  <div
                    class="progress-bar"
                    role="progressbar"
                    [style.width.%]="apiProgress.totalBatches > 0 ? (apiProgress.currentBatch / apiProgress.totalBatches) * 100 : 0"
                  ></div>
                </div>
              </div>

              <!-- Results -->
              <div *ngIf="apiSyncResult && !apiSyncing" class="mt-3">
                <div [class]="apiSyncResult.success ? 'alert alert-success' : 'alert alert-warning'" class="small mb-2">
                  <div class="fw-semibold mb-1">
                    {{ apiSyncResult.success ? 'API Sync Complete' : 'API Sync Failed' }}
                  </div>
                  <div>Updated: {{ apiSyncResult.updatedCount }} line items</div>
                  <div *ngIf="apiSyncResult.notFoundCount > 0" class="text-warning">
                    Not found in API: {{ apiSyncResult.notFoundCount }} line items
                    ({{ apiSyncResult.notFoundParts.length }} unique parts)
                  </div>
                </div>

                <div *ngIf="apiSyncResult.errors.length > 0" class="alert alert-danger small mb-2">
                  <div class="fw-semibold mb-1">Errors:</div>
                  <ul class="mb-0 ps-3">
                    <li *ngFor="let error of apiSyncResult.errors">{{ error }}</li>
                  </ul>
                </div>

                <div *ngIf="apiSyncResult.notFoundParts.length > 0 && apiSyncResult.notFoundParts.length <= 20">
                  <button
                    class="btn btn-sm btn-outline-secondary"
                    type="button"
                    (click)="showApiNotFoundParts = !showApiNotFoundParts"
                  >
                    {{ showApiNotFoundParts ? 'Hide' : 'Show' }} {{ apiSyncResult.notFoundParts.length }} not found parts
                  </button>
                  <div *ngIf="showApiNotFoundParts" class="mt-2 p-2 bg-body-secondary rounded small" style="max-height: 150px; overflow-y: auto;">
                    <code *ngFor="let part of apiSyncResult.notFoundParts; let last = last">
                      {{ part }}{{ last ? '' : ', ' }}
                    </code>
                  </div>
                </div>
              </div>

              <div class="small text-muted mt-3">
                <div class="fw-medium text-body mb-1">What gets updated:</div>
                <ul class="mb-1 ps-3">
                  <li><strong>Qty Available</strong> - Current stock on hand</li>
                  <li><strong>Qty On Order</strong> - Quantity on order</li>
                  <li><strong>Description</strong> - Part description</li>
                </ul>
                <div class="small">
                  Pick counts, locations, and quantities needed are NOT affected. Parts are synced in batches of 30.
                </div>
              </div>
            </div>
          </div>

          <!-- Data Backup -->
          <div class="card mb-4">
            <div class="card-header">
              <span class="fw-semibold">
                <i class="bi bi-database me-2"></i>Data Backup
              </span>
            </div>
            <div class="card-body">
              <p class="small text-muted mb-3">
                Export all application data to an Excel file for backup or migration purposes.
                Includes: Orders, Tools, Line Items, Picks, Issues, Parts Catalog, and BOM Templates.
              </p>

              <button
                class="btn btn-outline-primary w-100"
                [disabled]="exportingBackup"
                (click)="exportBackup()"
              >
                <i class="bi me-2" [class]="exportingBackup ? 'bi-arrow-clockwise spin' : 'bi-download'"></i>
                {{ exportingBackup ? 'Exporting...' : 'Export Full Backup' }}
              </button>

              <div *ngIf="backupExported" class="alert alert-success small mt-3 mb-0">
                <i class="bi bi-check-circle me-2"></i>
                Backup exported successfully!
              </div>
            </div>
          </div>

          <!-- Tips -->
          <div class="card">
            <div class="card-header">
              <span class="fw-semibold">
                <i class="bi bi-lightbulb me-2"></i>Tips
              </span>
            </div>
            <div class="card-body">
              <ul class="small text-muted mb-0">
                <li class="mb-2">Use the search bar to quickly find orders by SO#, PO#, or customer name</li>
                <li class="mb-2">Click on any order to view details and start picking</li>
                <li class="mb-2">The Dashboard shows orders that are due soon or overdue</li>
                <li class="mb-2">Import Excel files to quickly create orders with their parts lists</li>
                <li class="mb-2">Sync inventory regularly to keep stock quantities up to date</li>
                <li>Export backups periodically to prevent data loss</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .spin {
      animation: spin 1s linear infinite;
    }

    @keyframes spin {
      from { transform: rotate(0deg); }
      to { transform: rotate(360deg); }
    }
  `]
})
export class SettingsComponent implements OnInit, OnDestroy {
  userName = '';
  theme: 'light' | 'dark' | 'system' = 'system';
  tagPrintingEnabled = false;

  // App status
  isOnline = navigator.onLine;
  offlineQueueCount = 0;
  isSyncing = false;
  canInstallPwa = false;
  private deferredPrompt: any = null;

  // Inventory sync
  inventoryFile: File | null = null;
  inventorySyncing = false;
  inventorySyncResult: InventorySyncResult | null = null;
  showNotFoundParts = false;

  // Part List sync
  partListFile: File | null = null;
  partListSyncing = false;
  partListSyncResult: PartListSyncResult | null = null;

  // API sync
  apiPassword = '';
  apiSyncing = false;
  apiProgress: ApiSyncProgress | null = null;
  apiSyncResult: ApiSyncResult | null = null;
  showApiNotFoundParts = false;
  private readonly API_SYNC_PASSWORD = '33214551';

  get isApiPasswordCorrect(): boolean {
    return this.apiPassword === this.API_SYNC_PASSWORD;
  }

  // Backup
  exportingBackup = false;
  backupExported = false;

  private subscriptions: Subscription[] = [];

  constructor(
    private settingsService: SettingsService,
    private inventorySyncService: InventorySyncService,
    private partListSyncService: PartListSyncService,
    private apiSyncService: ApiSyncService,
    private excelService: ExcelService,
    private offlineService: OfflineService
  ) {}

  ngOnInit(): void {
    this.subscriptions.push(
      this.settingsService.settings$.subscribe(settings => {
        this.userName = settings.user_name;
        this.theme = settings.theme;
        this.tagPrintingEnabled = settings.tagPrintingEnabled === true;
      }),
      this.offlineService.isOnline$.subscribe(online => {
        this.isOnline = online;
      }),
      this.offlineService.queue$.subscribe(queue => {
        this.offlineQueueCount = queue.length;
      }),
      this.offlineService.isSyncing$.subscribe(syncing => {
        this.isSyncing = syncing;
      }),
      this.inventorySyncService.syncing$.subscribe(syncing => {
        this.inventorySyncing = syncing;
      }),
      this.inventorySyncService.lastSyncResult$.subscribe(result => {
        this.inventorySyncResult = result;
      }),
      this.partListSyncService.syncing$.subscribe(syncing => {
        this.partListSyncing = syncing;
      }),
      this.partListSyncService.lastSyncResult$.subscribe(result => {
        this.partListSyncResult = result;
      }),
      this.apiSyncService.syncing$.subscribe(syncing => {
        this.apiSyncing = syncing;
      }),
      this.apiSyncService.progress$.subscribe(progress => {
        this.apiProgress = progress;
      }),
      this.apiSyncService.lastSyncResult$.subscribe(result => {
        this.apiSyncResult = result;
      })
    );

    // Listen for PWA install prompt
    window.addEventListener('beforeinstallprompt', (e: any) => {
      e.preventDefault();
      this.deferredPrompt = e;
      this.canInstallPwa = true;
    });

    // Listen for online/offline events
    window.addEventListener('online', () => this.isOnline = true);
    window.addEventListener('offline', () => this.isOnline = false);
  }

  ngOnDestroy(): void {
    this.subscriptions.forEach(sub => sub.unsubscribe());
  }

  saveUserName(): void {
    this.settingsService.setUserName(this.userName);
  }

  saveTheme(): void {
    this.settingsService.setTheme(this.theme);
  }

  saveTagPrinting(): void {
    this.settingsService.setTagPrintingEnabled(this.tagPrintingEnabled);
  }

  // Inventory Sync
  onInventoryFileSelected(event: Event): void {
    const input = event.target as HTMLInputElement;
    if (input.files && input.files.length > 0) {
      this.inventoryFile = input.files[0];
      this.inventorySyncResult = null;
    }
  }

  async syncInventory(): Promise<void> {
    if (!this.inventoryFile) return;
    await this.inventorySyncService.syncInventory(this.inventoryFile);
  }

  // Part List Sync
  onPartListFileSelected(event: Event): void {
    const input = event.target as HTMLInputElement;
    if (input.files && input.files.length > 0) {
      this.partListFile = input.files[0];
      this.partListSyncResult = null;
    }
  }

  async syncPartList(): Promise<void> {
    if (!this.partListFile) return;
    await this.partListSyncService.syncPartList(this.partListFile);
  }

  // API Sync
  async syncFromApi(): Promise<void> {
    if (!this.isApiPasswordCorrect) return;
    await this.apiSyncService.syncFromApi();
  }

  // Backup Export
  async exportBackup(): Promise<void> {
    this.exportingBackup = true;
    this.backupExported = false;
    try {
      await this.excelService.exportFullBackupToExcel();
      this.backupExported = true;
      setTimeout(() => this.backupExported = false, 5000);
    } catch (error) {
      console.error('Failed to export backup:', error);
    } finally {
      this.exportingBackup = false;
    }
  }

  // Offline Queue Sync
  async syncOfflineQueue(): Promise<void> {
    // This would need to be connected to the picks service
    // For now, just show that the functionality exists
    console.log('Sync offline queue triggered');
  }

  // PWA Install
  async installPwa(): Promise<void> {
    if (!this.deferredPrompt) return;

    this.deferredPrompt.prompt();
    const { outcome } = await this.deferredPrompt.userChoice;

    if (outcome === 'accepted') {
      this.canInstallPwa = false;
    }
    this.deferredPrompt = null;
  }
}

// src/pages/Settings.tsx
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';
import { useSettings } from '@/hooks/useSettings';
import { SCHEMA_SQL, MIGRATION_QTY_ON_ORDER_SQL } from '@/lib/supabase';
import { useState, useRef } from 'react';
import { usePWA, useServiceWorker } from '@/hooks/usePWA';
import { useOnlineStatus, useOfflineQueue } from '@/hooks/useOffline';
import { usePartListSync } from '@/hooks/usePartListSync';
import { useApiSync } from '@/hooks/useApiSync';
import { useBackupExport } from '@/hooks/useBackupExport';
import { Download, RefreshCw, Wifi, WifiOff, Trash2, CloudOff, Upload, FileSpreadsheet, CheckCircle, AlertCircle, Database, HardDrive, ListChecks, Globe, Lock, Printer } from 'lucide-react';
import { Checkbox } from '@/components/ui/checkbox';

export function Settings() {
  const { settings, updateSettings } = useSettings();
  const [showSchema, setShowSchema] = useState(false);
  const [showMigration, setShowMigration] = useState(false);
  const [copied, setCopied] = useState(false);

  // PWA hooks
  const { isInstallable, isInstalled, install } = usePWA();
  const { needsRefresh, refresh } = useServiceWorker();
  const isOnline = useOnlineStatus();
  const { queueCount, clearQueue } = useOfflineQueue();

  // Part List sync
  const { syncPartList, syncing, lastSyncResult } = usePartListSync();
  const partListFileRef = useRef<HTMLInputElement>(null);

  // API sync
  const { syncFromApi, syncing: apiSyncing, progress: apiProgress, lastSyncResult: apiSyncResult } = useApiSync();
  const [apiPassword, setApiPassword] = useState('');
  const API_SYNC_PASSWORD = '33214551';
  const isApiPasswordCorrect = apiPassword === API_SYNC_PASSWORD;

  const handleApiSync = async () => {
    if (!isApiPasswordCorrect) return;
    await syncFromApi();
  };

  // Backup export
  const { exportBackup, exporting: exportingBackup, error: backupError } = useBackupExport();
  const [backupSuccess, setBackupSuccess] = useState(false);

  const handleExportBackup = async () => {
    setBackupSuccess(false);
    const success = await exportBackup();
    if (success) {
      setBackupSuccess(true);
      setTimeout(() => setBackupSuccess(false), 3000);
    }
  };

  const handleCopySchema = async () => {
    await navigator.clipboard.writeText(SCHEMA_SQL);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleCopyMigration = async () => {
    await navigator.clipboard.writeText(MIGRATION_QTY_ON_ORDER_SQL);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePartListFileSelect = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      await syncPartList(file);
      // Reset file input
      if (partListFileRef.current) {
        partListFileRef.current.value = '';
      }
    }
  };

  const handleClearQueue = () => {
    if (window.confirm(`Are you sure you want to clear ${queueCount} pending pick(s)? This action cannot be undone.`)) {
      clearQueue();
    }
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold">Settings</h1>
        <p className="text-muted-foreground">
          Configure your preferences and app settings
        </p>
      </div>

      {/* Part List Sync */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <ListChecks className="h-5 w-5" />
            Part List Sync
          </CardTitle>
          <CardDescription>
            Update part locations, descriptions, and quantities from Parts List export
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="flex items-center gap-4">
            <input
              ref={partListFileRef}
              type="file"
              accept=".xlsx,.xls"
              onChange={handlePartListFileSelect}
              className="hidden"
              id="partlist-file"
            />
            <Button
              onClick={() => partListFileRef.current?.click()}
              disabled={syncing}
              className="gap-2"
            >
              {syncing ? (
                <>
                  <RefreshCw className="h-4 w-4 animate-spin" />
                  Syncing...
                </>
              ) : (
                <>
                  <Upload className="h-4 w-4" />
                  Import Parts List
                </>
              )}
            </Button>
            <span className="text-sm text-muted-foreground">
              Supports .xlsx files (e.g., Parts List.xlsx)
            </span>
          </div>

          {lastSyncResult && (
            <div className={`p-4 rounded-lg border ${
              lastSyncResult.success
                ? 'border-green-200 bg-green-50 dark:border-green-800 dark:bg-green-900/20'
                : 'border-red-200 bg-red-50 dark:border-red-800 dark:bg-red-900/20'
            }`}>
              <div className="flex items-start gap-3">
                {lastSyncResult.success ? (
                  <CheckCircle className="h-5 w-5 text-green-600 mt-0.5" />
                ) : (
                  <AlertCircle className="h-5 w-5 text-red-600 mt-0.5" />
                )}
                <div className="flex-1">
                  <p className={`font-medium ${
                    lastSyncResult.success ? 'text-green-800 dark:text-green-200' : 'text-red-800 dark:text-red-200'
                  }`}>
                    {lastSyncResult.success ? 'Sync Complete' : 'Sync Failed'}
                  </p>
                  <div className="mt-2 text-sm space-y-1">
                    <p>Updated: <strong>{lastSyncResult.updatedCount}</strong> line items</p>
                    {lastSyncResult.notFoundCount > 0 && (
                      <p className="text-amber-600 dark:text-amber-400">
                        Not found in Parts List: <strong>{lastSyncResult.notFoundCount}</strong> line items
                        ({lastSyncResult.notFoundParts.length} unique parts)
                      </p>
                    )}
                    {lastSyncResult.notFoundParts.length > 0 && lastSyncResult.notFoundParts.length <= 10 && (
                      <details className="mt-2">
                        <summary className="cursor-pointer text-muted-foreground">
                          Show missing part numbers
                        </summary>
                        <ul className="mt-1 ml-4 text-xs font-mono">
                          {lastSyncResult.notFoundParts.map(p => (
                            <li key={p}>{p}</li>
                          ))}
                        </ul>
                      </details>
                    )}
                    {lastSyncResult.errors.length > 0 && (
                      <div className="mt-2 text-red-600 dark:text-red-400">
                        {lastSyncResult.errors.map((err, i) => (
                          <p key={i}>{err}</p>
                        ))}
                      </div>
                    )}
                  </div>
                </div>
              </div>
            </div>
          )}

          <div className="text-sm text-muted-foreground space-y-2">
            <p className="font-medium text-foreground">What gets updated:</p>
            <ul className="list-disc list-inside space-y-1 ml-2">
              <li><strong>Location</strong> - Storage location</li>
              <li><strong>Description</strong> - Part description</li>
              <li><strong>Qty Available</strong> - Current stock on hand</li>
              <li><strong>Qty On Order</strong> - Quantity on order (optional)</li>
            </ul>
            <p className="text-xs mt-2">
              Pick counts are preserved - only metadata is updated.
            </p>
          </div>

          {/* Migration SQL for qty_on_order column */}
          <div className="pt-4 border-t">
            <Button
              variant="outline"
              size="sm"
              onClick={() => setShowMigration(!showMigration)}
            >
              {showMigration ? 'Hide' : 'Show'} Migration SQL
            </Button>

            {showMigration && (
              <div className="mt-4">
                <div className="flex items-center justify-between mb-2">
                  <Label className="text-sm">Run this SQL if qty_on_order column is missing:</Label>
                  <Button size="sm" variant="secondary" onClick={handleCopyMigration}>
                    {copied ? 'Copied!' : 'Copy'}
                  </Button>
                </div>
                <pre className="bg-muted p-3 rounded-lg text-xs overflow-x-auto">
                  {MIGRATION_QTY_ON_ORDER_SQL}
                </pre>
              </div>
            )}
          </div>
        </CardContent>
      </Card>

      {/* API Sync */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Globe className="h-5 w-5" />
            API Sync
          </CardTitle>
          <CardDescription>
            Sync qty available, qty on order, and descriptions directly from the Andrews Tool API
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-3">
            <div className="space-y-2">
              <Label htmlFor="api-password" className="flex items-center gap-1.5">
                <Lock className="h-3.5 w-3.5" />
                Password Required
              </Label>
              <div className="flex items-center gap-3 max-w-md">
                <Input
                  id="api-password"
                  type="password"
                  placeholder="Enter sync password"
                  value={apiPassword}
                  onChange={(e) => setApiPassword(e.target.value)}
                />
                <Button
                  onClick={handleApiSync}
                  disabled={!isApiPasswordCorrect || apiSyncing}
                  className="gap-2 whitespace-nowrap"
                >
                  {apiSyncing ? (
                    <>
                      <RefreshCw className="h-4 w-4 animate-spin" />
                      Syncing...
                    </>
                  ) : (
                    <>
                      <Globe className="h-4 w-4" />
                      Sync from API
                    </>
                  )}
                </Button>
              </div>
            </div>
          </div>

          {/* Progress */}
          {apiSyncing && apiProgress && (
            <div className="space-y-2">
              <div className="flex items-center justify-between text-sm">
                <span className="text-muted-foreground">{apiProgress.status}</span>
                <span className="font-medium">
                  {apiProgress.currentBatch} / {apiProgress.totalBatches}
                </span>
              </div>
              <Progress
                value={
                  apiProgress.totalBatches > 0
                    ? (apiProgress.currentBatch / apiProgress.totalBatches) * 100
                    : 0
                }
              />
            </div>
          )}

          {/* Results */}
          {apiSyncResult && !apiSyncing && (
            <div className={`p-4 rounded-lg border ${
              apiSyncResult.success
                ? 'border-green-200 bg-green-50 dark:border-green-800 dark:bg-green-900/20'
                : 'border-red-200 bg-red-50 dark:border-red-800 dark:bg-red-900/20'
            }`}>
              <div className="flex items-start gap-3">
                {apiSyncResult.success ? (
                  <CheckCircle className="h-5 w-5 text-green-600 mt-0.5" />
                ) : (
                  <AlertCircle className="h-5 w-5 text-red-600 mt-0.5" />
                )}
                <div className="flex-1">
                  <p className={`font-medium ${
                    apiSyncResult.success ? 'text-green-800 dark:text-green-200' : 'text-red-800 dark:text-red-200'
                  }`}>
                    {apiSyncResult.success ? 'API Sync Complete' : 'API Sync Failed'}
                  </p>
                  <div className="mt-2 text-sm space-y-1">
                    <p>Updated: <strong>{apiSyncResult.updatedCount}</strong> line items</p>
                    {apiSyncResult.notFoundCount > 0 && (
                      <p className="text-amber-600 dark:text-amber-400">
                        Not found in API: <strong>{apiSyncResult.notFoundCount}</strong> line items
                        ({apiSyncResult.notFoundParts.length} unique parts)
                      </p>
                    )}
                    {apiSyncResult.notFoundParts.length > 0 && apiSyncResult.notFoundParts.length <= 20 && (
                      <details className="mt-2">
                        <summary className="cursor-pointer text-muted-foreground">
                          Show missing part numbers
                        </summary>
                        <ul className="mt-1 ml-4 text-xs font-mono">
                          {apiSyncResult.notFoundParts.map(p => (
                            <li key={p}>{p}</li>
                          ))}
                        </ul>
                      </details>
                    )}
                    {apiSyncResult.errors.length > 0 && (
                      <div className="mt-2 text-red-600 dark:text-red-400">
                        {apiSyncResult.errors.map((err, i) => (
                          <p key={i}>{err}</p>
                        ))}
                      </div>
                    )}
                  </div>
                </div>
              </div>
            </div>
          )}

          <div className="text-sm text-muted-foreground space-y-2">
            <p className="font-medium text-foreground">What gets updated:</p>
            <ul className="list-disc list-inside space-y-1 ml-2">
              <li><strong>Qty Available</strong> - Current stock on hand</li>
              <li><strong>Qty On Order</strong> - Quantity on order</li>
              <li><strong>Description</strong> - Part description</li>
            </ul>
            <p className="text-xs mt-2">
              Pick counts, locations, and quantities needed are NOT affected. Parts are synced in batches of 30.
            </p>
          </div>
        </CardContent>
      </Card>

      {/* Data Backup */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <HardDrive className="h-5 w-5" />
            Data Backup
          </CardTitle>
          <CardDescription>
            Export all data to an Excel file for backup or recovery
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="flex items-center gap-4">
            <Button
              onClick={handleExportBackup}
              disabled={exportingBackup}
              className="gap-2"
            >
              {exportingBackup ? (
                <>
                  <RefreshCw className="h-4 w-4 animate-spin" />
                  Exporting...
                </>
              ) : (
                <>
                  <Database className="h-4 w-4" />
                  Export Full Backup
                </>
              )}
            </Button>
            {backupSuccess && (
              <span className="text-sm text-green-600 dark:text-green-400 flex items-center gap-1">
                <CheckCircle className="h-4 w-4" />
                Backup exported successfully!
              </span>
            )}
          </div>

          {backupError && (
            <div className="p-4 rounded-lg border border-red-200 bg-red-50 dark:border-red-800 dark:bg-red-900/20">
              <div className="flex items-start gap-3">
                <AlertCircle className="h-5 w-5 text-red-600 mt-0.5" />
                <div>
                  <p className="font-medium text-red-800 dark:text-red-200">Backup Failed</p>
                  <p className="text-sm text-red-700 dark:text-red-300 mt-1">{backupError}</p>
                </div>
              </div>
            </div>
          )}

          <div className="text-sm text-muted-foreground space-y-2">
            <p className="font-medium text-foreground">What gets exported:</p>
            <ul className="list-disc list-inside space-y-1 ml-2">
              <li><strong>Orders</strong> - All sales orders with status and dates</li>
              <li><strong>Tools</strong> - All tools within orders</li>
              <li><strong>Line Items</strong> - All parts with quantities and locations</li>
              <li><strong>Picks</strong> - Complete pick history (who, what, when)</li>
              <li><strong>Issues</strong> - Reported issues and resolutions</li>
              <li><strong>Parts Catalog</strong> - Saved part numbers and descriptions</li>
              <li><strong>BOM Templates</strong> - Saved bill of materials templates</li>
            </ul>
            <p className="text-xs mt-3 p-2 bg-muted rounded">
              Tip: Export a backup regularly (weekly) and save the files to a safe location
              like OneDrive, Google Drive, or an external drive.
            </p>
          </div>
        </CardContent>
      </Card>

      {/* Tag Printing */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Printer className="h-5 w-5" />
            Tag Printing
          </CardTitle>
          <CardDescription>
            Print part tags after picking for Brother P-Touch QL500 label printer
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="flex items-center justify-between p-3 rounded-lg bg-muted/50">
            <div className="flex items-center gap-3">
              <Printer className="h-5 w-5 text-primary" />
              <div>
                <p className="font-medium">Enable Tag Printing</p>
                <p className="text-sm text-muted-foreground">
                  Show print dialog after picking parts
                </p>
              </div>
            </div>
            <label className="relative inline-flex items-center cursor-pointer">
              <Checkbox
                checked={settings.tagPrintingEnabled === true}
                onCheckedChange={(checked) => updateSettings({ tagPrintingEnabled: checked === true })}
                className="h-5 w-5"
              />
            </label>
          </div>

          <div className="text-sm text-muted-foreground space-y-2">
            <p className="font-medium text-foreground">Printer Setup:</p>
            <ul className="list-disc list-inside space-y-1 ml-2">
              <li><strong>Printer:</strong> Brother P-Touch QL500</li>
              <li><strong>Label Size:</strong> 0.66" x 3.4" (landscape)</li>
              <li>Each individual part gets its own tag (qty=5 prints 5 tags)</li>
            </ul>
            <p className="text-xs mt-3 p-2 bg-muted rounded">
              Tip: Set the Brother QL500 as your default printer for faster printing,
              or select it each time in the print dialog.
            </p>
          </div>
        </CardContent>
      </Card>

      {/* User Settings */}
      <Card>
        <CardHeader>
          <CardTitle>User Settings</CardTitle>
          <CardDescription>
            Your name will be recorded with picks for tracking purposes
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="user_name">Your Name</Label>
            <Input
              id="user_name"
              placeholder="Enter your name"
              value={settings.user_name}
              onChange={(e) => updateSettings({ user_name: e.target.value })}
              className="max-w-md"
            />
            <p className="text-sm text-muted-foreground">
              This name will be attached to your picks so others can see who picked what.
            </p>
          </div>
        </CardContent>
      </Card>

      {/* PWA / Offline Settings */}
      <Card>
        <CardHeader>
          <CardTitle>App Installation & Offline</CardTitle>
          <CardDescription>
            Install the app for offline access and better performance
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          {/* Connection Status */}
          <div className="flex items-center justify-between p-3 rounded-lg bg-muted/50">
            <div className="flex items-center gap-3">
              {isOnline ? (
                <Wifi className="h-5 w-5 text-green-500" />
              ) : (
                <WifiOff className="h-5 w-5 text-amber-500" />
              )}
              <div>
                <p className="font-medium">Connection Status</p>
                <p className="text-sm text-muted-foreground">
                  {isOnline ? 'You are online' : 'You are offline - picks will be queued'}
                </p>
              </div>
            </div>
            <span
              className={`px-2 py-1 rounded-full text-xs font-medium ${
                isOnline
                  ? 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400'
                  : 'bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400'
              }`}
            >
              {isOnline ? 'Online' : 'Offline'}
            </span>
          </div>

          {/* Offline Queue */}
          {queueCount > 0 && (
            <div className="flex items-center justify-between p-3 rounded-lg border border-amber-200 bg-amber-50 dark:border-amber-800 dark:bg-amber-900/20">
              <div className="flex items-center gap-3">
                <CloudOff className="h-5 w-5 text-amber-500" />
                <div>
                  <p className="font-medium">Pending Picks</p>
                  <p className="text-sm text-muted-foreground">
                    {queueCount} pick(s) waiting to sync
                  </p>
                </div>
              </div>
              <Button
                variant="outline"
                size="sm"
                onClick={handleClearQueue}
                className="text-destructive hover:text-destructive"
              >
                <Trash2 className="h-4 w-4 mr-1" />
                Clear
              </Button>
            </div>
          )}

          {/* Install App */}
          <div className="flex items-center justify-between p-3 rounded-lg bg-muted/50">
            <div className="flex items-center gap-3">
              <Download className="h-5 w-5 text-primary" />
              <div>
                <p className="font-medium">Install App</p>
                <p className="text-sm text-muted-foreground">
                  {isInstalled
                    ? 'App is installed on this device'
                    : isInstallable
                      ? 'Install for offline access and quick launch'
                      : 'Installation not available in this browser'}
                </p>
              </div>
            </div>
            {isInstallable && !isInstalled && (
              <Button onClick={install} size="sm">
                <Download className="h-4 w-4 mr-1" />
                Install
              </Button>
            )}
            {isInstalled && (
              <span className="px-2 py-1 rounded-full text-xs font-medium bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400">
                Installed
              </span>
            )}
          </div>

          {/* Update Available */}
          {needsRefresh && (
            <div className="flex items-center justify-between p-3 rounded-lg border border-primary bg-primary/5">
              <div className="flex items-center gap-3">
                <RefreshCw className="h-5 w-5 text-primary" />
                <div>
                  <p className="font-medium">Update Available</p>
                  <p className="text-sm text-muted-foreground">
                    A new version of the app is ready
                  </p>
                </div>
              </div>
              <Button onClick={refresh} size="sm">
                <RefreshCw className="h-4 w-4 mr-1" />
                Update Now
              </Button>
            </div>
          )}

          {/* Offline Features Info */}
          <div className="text-sm text-muted-foreground space-y-2">
            <p className="font-medium text-foreground">Offline Features:</p>
            <ul className="list-disc list-inside space-y-1 ml-2">
              <li>View previously loaded orders and parts</li>
              <li>Record picks while offline (syncs when back online)</li>
              <li>Full app functionality without internet</li>
            </ul>
          </div>
        </CardContent>
      </Card>

      {/* Database Setup */}
      <Card>
        <CardHeader>
          <CardTitle>Database Setup</CardTitle>
          <CardDescription>
            Instructions for setting up Supabase backend
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2 text-sm">
            <p>To use this app with real-time sync, you need to:</p>
            <ol className="list-decimal list-inside space-y-2 ml-2">
              <li>Create a free account at <a href="https://supabase.com" target="_blank" rel="noopener noreferrer" className="text-primary underline">supabase.com</a></li>
              <li>Create a new project</li>
              <li>Go to the SQL Editor and run the schema below</li>
              <li>Copy your project URL and anon key from Settings &gt; API</li>
              <li>Create a <code className="bg-muted px-1 rounded">.env</code> file with:
                <pre className="bg-muted p-2 rounded mt-1 text-xs">
{`VITE_SUPABASE_URL=your-project-url
VITE_SUPABASE_ANON_KEY=your-anon-key`}
                </pre>
              </li>
              <li>Restart the development server</li>
            </ol>
          </div>

          <div className="pt-4 border-t">
            <Button
              variant="outline"
              onClick={() => setShowSchema(!showSchema)}
            >
              {showSchema ? 'Hide' : 'Show'} Database Schema
            </Button>

            {showSchema && (
              <div className="mt-4">
                <div className="flex items-center justify-between mb-2">
                  <Label>SQL Schema</Label>
                  <Button size="sm" variant="secondary" onClick={handleCopySchema}>
                    {copied ? 'Copied!' : 'Copy to Clipboard'}
                  </Button>
                </div>
                <pre className="bg-muted p-4 rounded-lg text-xs overflow-x-auto max-h-96">
                  {SCHEMA_SQL}
                </pre>
              </div>
            )}
          </div>
        </CardContent>
      </Card>

      {/* About */}
      <Card>
        <CardHeader>
          <CardTitle>About</CardTitle>
        </CardHeader>
        <CardContent className="text-sm text-muted-foreground">
          <p>Tool Pick List Tracker v1.0.0</p>
          <p className="mt-2">
            A web-based application for tracking tool pick lists across multiple
            devices, allowing multiple users to simultaneously mark parts as picked,
            track partial picks per tool, and view consolidated part status across
            all sales orders.
          </p>
          <p className="mt-2">
            This app works offline and can be installed as a Progressive Web App (PWA)
            for quick access from your home screen.
          </p>
        </CardContent>
      </Card>
    </div>
  );
}
